CREATE TABLE [dbo].[STAFFS] (
    [STAFFID] INT          NOT NULL,
    [TYPENO]  INT          NOT NULL,
    [NAME]    VARCHAR (50) NOT NULL,
    [PHONE]   VARCHAR (50) NOT NULL,
    [EMAIL]   VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([STAFFID] ASC),
    FOREIGN KEY ([TYPENO]) REFERENCES [dbo].[STAFFTYPE] ([TYPENO])
);

