CREATE TABLE [dbo].[TEACHINGSTAFF] (
    [STAFFNO]   INT          IDENTITY (1, 1) NOT NULL,
    [CLASSNAME] VARCHAR (50) NOT NULL,
    [SUBJECT]   VARCHAR (50) NOT NULL,
    [STAFFID]   INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([STAFFNO] ASC),
    FOREIGN KEY ([STAFFID]) REFERENCES [dbo].[STAFFS] ([STAFFID])
);

